/*
 * This Java source file was generated by the Gradle 'init' task.
 */


public class App {
    
    public void println(String text) {
        System.out.println(text);
    }

    public static void main(String[] args) {
        
        Trainer t = TrainerFactory.getInstance().generateTrainerWithCodemonT1(5);
        t.setName("Player");
        t.setMoney(20000);
        t.addItem(new Item("Capture Stone", "Captures Codemon (probably)", 99));
        HumanTrainerEntity player = new HumanTrainerEntity(t);
        GamePlay game = new GamePlay(player);
        game.play();
    }
}
