import static org.junit.Assert.assertEquals;

import java.util.ArrayList;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */


public class App {
    
    public void println(String text) {
        System.out.println(text);
    }

    /**
     * Main. You know, the main class.
     * @param args I forget what this is for.
     */
    public static void main(String[] args) {
        UI ui = new PredictableUI();
        Weather weather = new Weather(0);
        ArrayList<TrainerEntity> trainers = new ArrayList<TrainerEntity>();
        CodemonFactory monFac = CodemonFactory.getInstance();
        Trainer t = new Trainer(monFac.generateCodemonWithT1Moves(10));
        HumanTrainerEntity te = new HumanTrainerEntity(t);
        te.setUI(ui);
        Trainer t1 = new Trainer(monFac.generateCodemonWithT1Moves(5));
        ComputerEntity te1 = new ComputerEntity(t1);
        trainers.add(te);
        trainers.add(te1);
        BattleState battle = new BattleState(trainers, ui, weather);
        
        BeginningPhase phase = new BeginningPhase(trainers, ui, weather);
        AbstractPhase nextPhase = phase.performPhase();
        AbstractPhase np1 = nextPhase.performPhase();
        np1.getClass();
        int nextState = battle.processState();
        
        Trainer tr = trainers.get(0).getTrainer();
        tr.addMon(monFac.generateCodemonWithT1Moves(10));
        tr.addMon(monFac.generateCodemonWithT1Moves(10));
        tr.addMon(monFac.generateCodemonWithT1Moves(10));
        tr.addMon(monFac.generateCodemonWithT1Moves(10));
        tr.addMon(monFac.generateCodemonWithT1Moves(10));
        MenuState menu = new MenuState(trainers, ui, weather);
        menu.handleDetailedDescriptionMenu(0, -1);
        menu.handleDetailedDescriptionMenu(1, -1);
        menu.handleDetailedDescriptionMenu(2, -1);
        GamePlay game = new GamePlay(new PredictableUI());
        //GamePlay game = new GamePlay(new BlindIdiotUI());
        //GamePlay game = new GamePlay();
        game.play(50);
    }
}
