/*
 * This Java source file was generated by the Gradle 'init' task.
 */


public class App {
    
    public void println(String text) {
        System.out.println(text);
    }

    public static void main(String[] args) {
        
        
        GamePlay game = new GamePlay(new BlindIdiotUI());
        game.play(50);
    }
}
