/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ser316.hw5.dgallenb;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    
    public void println(String text) {
        System.out.println(text);
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
